# Generated by Django 2.0.8 on 2019-10-02 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('apellido', models.CharField(max_length=255, null=True)),
                ('dni', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=128, null=True)),
                ('legajo', models.CharField(max_length=32)),
                ('es_regular', models.BooleanField(default=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2, null=True)),
                ('telefono', models.CharField(max_length=32, null=True)),
                ('celular', models.CharField(max_length=32, null=True)),
                ('tiene_beca', models.BooleanField(default=False)),
                ('tiene_tutor', models.BooleanField(default=False)),
                ('tiene_pc', models.BooleanField(default=False)),
                ('tiene_pendrive', models.BooleanField(default=False)),
                ('tiene_portatil', models.BooleanField(default=False)),
                ('comentario', models.CharField(max_length=255, null=True)),
                ('observacion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoDeCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.CharField(max_length=3, null=True)),
                ('coeficiente', models.CharField(max_length=3, null=True)),
                ('cuatrimestre_inscripto', models.CharField(max_length=8, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(max_length=32, null=True)),
                ('nombre', models.CharField(max_length=128, null=True)),
                ('codigo', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaCursada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('A', 'A- Aprobado'), ('E', 'E- Pendiente de Aprobacion'), ('N', 'N- Reprobado'), ('P', 'P- Aprobado'), ('U', 'U- Ausente'), ('R', 'R- Reprobado'), ('V', 'V- Pendiente Virtual'), ('', 'Ausente de Examen')], max_length=2, null=True)),
                ('nota', models.CharField(choices=[('PA', 'Pendiente de Aprobacion'), ('A', 'Aprobado'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True)),
                ('fecha', models.DateField(null=True)),
                ('forma_aprobacion', models.CharField(max_length=32, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='core.Alumno')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='core.Carrera')),
                ('comision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Comision')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaEnPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('nucleo', models.CharField(choices=[('I', 'Introductoria'), ('B', 'Basica'), ('A', 'Avanzada'), ('C', 'Complementaria')], max_length=2, null=True)),
                ('creditos', models.IntegerField(null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('orden_cuatrimestral', models.IntegerField(null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Area')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Materia')),
                ('obligatorias', models.ManyToManyField(related_name='_materiaenplan_obligatorias_+', to='core.MateriaEnPlan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField(null=True)),
                ('anio', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreras', models.ManyToManyField(to='core.Carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlanDeEstudio'),
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='recomendadas',
            field=models.ManyToManyField(related_name='_materiaenplan_recomendadas_+', to='core.MateriaEnPlan'),
        ),
        migrations.AddField(
            model_name='materiacursada',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MateriaEnPlan'),
        ),
        migrations.AddField(
            model_name='comision',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Materia'),
        ),
        migrations.AddField(
            model_name='area',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carrera'),
        ),
        migrations.AddField(
            model_name='alumnodecarrera',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carrera'),
        ),
        migrations.AddField(
            model_name='alumnodecarrera',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PlanDeEstudio'),
        ),
    ]
