# Generated by Django 2.0.8 on 2018-08-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180829_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MateriaAprobada',
            new_name='MateriaCursada',
        ),
    ]
