# Generated by Django 2.0.8 on 2018-11-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180829_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='persona',
            new_name='datos_personales',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='persona',
            new_name='datos_personales',
        ),
    ]
