# Generated by Django 2.0.8 on 2018-11-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181110_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
