# Generated by Django 2.0.8 on 2018-11-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181110_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='codigo',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='nombre',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
