# Generated by Django 2.0.8 on 2018-11-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181110_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materiaenplan',
            name='creditos',
            field=models.IntegerField(default=0),
        ),
    ]
