# Generated by Django 2.0.8 on 2018-11-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181110_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeestudio',
            name='materias',
            field=models.ManyToManyField(to='core.MateriaEnPlan'),
        ),
    ]
