# Generated by Django 2.0.8 on 2018-11-10 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181110_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='promedio',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='materiacursada',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='core.Alumno'),
        ),
    ]
