# Generated by Django 2.0.8 on 2018-11-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181110_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
