# Generated by Django 2.0.8 on 2019-06-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181113_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorEnComision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=64)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comision')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persona')),
            ],
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='comision',
        ),
        migrations.AddField(
            model_name='alumno',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PlanDeEstudio'),
        ),
    ]
