# Generated by Django 2.0.8 on 2019-06-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190601_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesorencomision',
            name='datos_personales',
        ),
        migrations.AddField(
            model_name='profesorencomision',
            name='profesor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Profesor'),
            preserve_default=False,
        ),
    ]
