# Generated by Django 2.0.8 on 2019-06-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190601_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandeestudio',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
