# Generated by Django 2.0.8 on 2019-06-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190602_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoDeCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.CharField(max_length=3, null=True)),
                ('cuatrimestre_inscripto', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='datos_personales',
        ),
        migrations.RemoveField(
            model_name='profesorencomision',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='profesorencomision',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='carreras',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='cuatrimestre_inscripto',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='datos_personales',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='promedio',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='materiacursada',
            name='materia',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiacursada',
            name='anio',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiacursada',
            name='comision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Comision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiacursada',
            name='cuatrimestre',
            field=models.CharField(choices=[('1', 'C1'), ('2', 'C2')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='codigo',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plandeestudio',
            name='anio',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materiacursada',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='core.AlumnoDeCarrera'),
        ),
        migrations.AlterField(
            model_name='materiacursada',
            name='nota',
            field=models.CharField(choices=[('C', 'Cursando'), ('EQ', 'Equivalencia'), ('AP', 'Aprobado'), ('D', 'Desaprobado'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='C', max_length=3),
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='ProfesorEnComision',
        ),
        migrations.AddField(
            model_name='alumnodecarrera',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Alumno'),
        ),
        migrations.AddField(
            model_name='alumnodecarrera',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carrera'),
        ),
        migrations.AddField(
            model_name='alumnodecarrera',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlanDeEstudio'),
        ),
    ]
