# Generated by Django 2.0.8 on 2019-06-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190619_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='planes',
        ),
        migrations.AddField(
            model_name='plandeestudio',
            name='carrera',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Carrera'),
            preserve_default=False,
        ),
    ]
