# Generated by Django 2.0.8 on 2019-06-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190619_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandeestudio',
            name='materias',
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.PlanDeEstudio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materiacursada',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='core.Alumno'),
        ),
    ]
