# Generated by Django 2.0.8 on 2019-06-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190619_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiacursada',
            name='materia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Materia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materiacursada',
            name='comision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Comision'),
        ),
    ]
