# Generated by Django 2.0.8 on 2019-08-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190619_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnodecarrera',
            name='coeficiente',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
