# Generated by Django 2.0.8 on 2019-09-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_materiacursada_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='alumnodecarrera',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PlanDeEstudio'),
        ),
    ]
