# Generated by Django 2.0.8 on 2019-09-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190905_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiacursada',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='materiacursada',
            name='cuatrimestre',
            field=models.CharField(choices=[('1', 'C1'), ('2', 'C2')], max_length=1, null=True),
        ),
    ]
