# Generated by Django 2.0.8 on 2019-09-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190905_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='materiaenplan',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
