# Generated by Django 2.0.8 on 2019-09-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190923_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaenplan',
            name='tipo',
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='nucleo',
            field=models.CharField(choices=[('I', 'Introductoria'), ('B', 'Basica'), ('A', 'Avanzada'), ('C', 'Complementaria')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='orden_cuatrimestral',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materiacursada',
            name='nota',
            field=models.CharField(choices=[('C', 'Cursando'), ('EQ', 'Equivalencia'), ('AP', 'Aprobado'), ('D', 'Desaprobado'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
    ]
