# Generated by Django 2.0.8 on 2019-09-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190929_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiacursada',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='materiacursada',
            name='cuatrimestre',
        ),
        migrations.AddField(
            model_name='materiacursada',
            name='forma_aprobacion',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
