# Generated by Django 2.0.8 on 2019-10-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190929_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiacursada',
            name='nota',
            field=models.CharField(choices=[('PA', 'Pendiente de Aprobacion'), ('A', 'Aprobado'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='materiacursada',
            name='resultado',
            field=models.CharField(choices=[('A', 'A- Aprobado'), ('E', 'E- Pendiente de Aprobacion'), ('N', 'N- Reprobado'), ('P', 'P- Aprobado'), ('U', 'U- Ausente'), ('R', 'R- Reprobado'), ('V', 'V- Pendiente Virtual'), ('', 'Ausente de Examen')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='materiaenplan',
            name='creditos',
            field=models.IntegerField(null=True),
        ),
    ]
