# Generated by Django 2.0.8 on 2019-10-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20191001_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaenplan',
            name='obligatorias',
            field=models.ManyToManyField(null=True, related_name='_materiaenplan_obligatorias_+', to='core.MateriaEnPlan'),
        ),
        migrations.AddField(
            model_name='materiaenplan',
            name='recomendadas',
            field=models.ManyToManyField(null=True, related_name='_materiaenplan_recomendadas_+', to='core.MateriaEnPlan'),
        ),
    ]
