# Generated by Django 2.0.8 on 2019-10-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20191001_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaenplan',
            name='obligatorias',
            field=models.ManyToManyField(related_name='_materiaenplan_obligatorias_+', to='core.MateriaEnPlan'),
        ),
        migrations.AlterField(
            model_name='materiaenplan',
            name='recomendadas',
            field=models.ManyToManyField(related_name='_materiaenplan_recomendadas_+', to='core.MateriaEnPlan'),
        ),
    ]
