# Generated by Django 2.0.8 on 2019-10-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20191002_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiacursada',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MateriaEnPlan'),
        ),
    ]
