# Generated by Django 2.0.8 on 2019-10-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20191002_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeestudio',
            name='anio',
            field=models.IntegerField(),
        ),
    ]
